services:
  server:
    build:
      context: ./client
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@altametrics-take-home-assessment-db-1:5432/postgres?schema=public
    ports:
      - 3000:3000
    depends_on:
       db:
         condition: service_healthy


  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

